server {
    listen 80;
    server_name techgen.umt.edu.vn;
    server_tokens off;

    # Xác thực SSL Certbot
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Chuyển hướng HTTP -> HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name techgen.umt.edu.vn;
    server_tokens off;

    ssl_certificate /etc/letsencrypt/live/techgen.umt.edu.vn/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/techgen.umt.edu.vn/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    client_max_body_size 50M;

    # 1. API BACKEND
    # Chuyển request ra ngoài máy chủ VPS (Nơi NestJS đang chạy port 4000)
    # Dùng 172.17.0.1 là IP Gateway mặc định để Docker gọi ra Host
    location /api/ {
        proxy_pass http://172.17.0.1:4000/api/; 
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # 2. ẢNH UPLOAD
    # Đọc từ volume đã map (/var/www/uploads)
    location /uploads/ {
        alias /var/www/uploads/;
        autoindex off;
        access_log off;
    }

    # 3. FRONTEND
    # Chuyển request sang container Next.js (nội bộ Docker, tên service là umt-techgen-web)
    location / {
        proxy_pass http://umt-techgen-web:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
    }
}